### ISSUE TITLE
Mozilla adding bloat like Pocket

### ISSUE THREAD

**Issue by Gitoffthelawn** [CHEF-KOCH/BetterFireFox#1]
Great start on the project!

Here is another item:

- Bloat like Pocket has been added.  To my knowledge, this is a third-party extension that has been added and uses non-Mozilla servers to store data.  Things like this should be left as extensions.

**Comment by CHEF-KOCH** [comment]
I added everyone from user.js as 'supporter', you guys can add yourself and edit whatever you think is necessary without 'asking' me, I trust you on that, and in case something is wrong we simply can revert it or/and start then the discussion.
