### ISSUE TITLE
PaleMoon List?

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/BetterFirefox#11]
Someone mentioned over [here](http://www.ghacks.net/2016/06/07/firefox-49-multi-process-architecture/#comment-3918527) that there exist already an identical list?! Anyone know about this? Seems my fault because I never watched PaleMoon forums before since I not see any 'future' in this project.

**Comment by Roman-Nopantski** [comment]
I searched and browsed the forums and can't find anything. I think the poster was simply referring to the fact that what you want to achieve and the direction Palemoon went has similarities. I don't think there is an actual list anywhere.

**Comment by CHEF-KOCH** [comment]
> Just ask moonchild if you get no reply, he's very contactable, friendly and helpful. He replied within minutes when I emailed him about palemoon entries for the ghacks user.js.

I think I will contact them, but I'm unsure because PaleMoon use a different engine with (maybe) other configs and toggles. 

I will close and possible re-open if there is any real process.
