### ISSUE TITLE
Make Sync an extension (installed by default, like pocket and loop)

### ISSUE THREAD

**Issue by N4melessGitter** [CHEF-KOCH/BetterFirefox#13]
I agree with removing pocket and loop from a default install, but would like it for Mozilla to make Sync an extension in the folder where pocket and loop currently reside. So people who don't need/want Sync can remove the file after each upgrade and get a leaner browser without all those Login to sync prompts etc.

**Comment by CHEF-KOCH** [comment]
Sync will never be an extension.
