### ISSUE TITLE
How safe is internal PDF reader to say Sumatra?

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [CHEF-KOCH/BetterFirefox#17]
I have disabled the internal PDF reader since it was introduced into Firefox because I read articles many years ago detailing how it was a terrible idea from a security perspective, so would I benefit from enabling it now? Has anything changed?

I certainly like the idea from a convenience perspective, but from a security standpoint are third party readers such as Sumatra PDF better? Or was this concern over blown and click bait?

I am asking this because you listed the internal PDF reader as a positive thing for Firefox and I wondered if something had changed or if the articles I read so long ago were just hype.

Thanks for your time.

**Comment by CHEF-KOCH** [comment]
There is a blacklist for permissions, so theoretically it's more secure now. But I personally also use SumatraPDF.
