### ISSUE TITLE
Firefox lost the browser battle once and for all - Browser Stats 

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/BetterFirefox#18]
Sad news for everyone, I was submitting everything to Mozilla and I got feedback back in the meantime. Mozilla also changed a lot of stuff in the time between my reply and today.

The thing is I don't believe anymore in Firefox and so also not the [ex tech Mozilla chef.](https://andreasgal.com/2017/07/19/firefox-marketshare-revisited/) He published his numbers [here](http://gs.statcounter.com/) which shows that the battle is already over.  

![infografik_427_globale_marktanteile_webbrowser_n-031b7e88c81bd222](https://user-images.githubusercontent.com/727123/28530432-194f9366-7094-11e7-9ecd-2f65eb8d8312.jpeg)

I do need to agree, because the recent changes Firefox made are copy & paste from Chrome and why do I should use a clone instead of the original (which also works better on certain things), especially because Google controls the entire web?! I do not think it has to do with the fact that Google advertise his browser more (it's their right). It's the fact that Google makes (especially on security related topics) faster changes.

At this point I not close this repo here but I put everything on hold till I get an idea how the community can handle this. But I'm not optimistic here.

**Comment by licaon-kter** [comment]
So, back? What's new?
