### ISSUE TITLE
Project Reboot v3.0  

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/BetterFirefox#19]
1. Project gets a re-launch 2018
2. Since there is a lot of done and adopted in _Quantum_ we need to remove old stuff which is still mentioned in the Readme
3. One Mozilla developer now stays directly in contact with us
4. Using stuff like user.js doesn't help anymore, instead we should guide people which addons and settings are '_good_'. Instead, holes needs to be fixed directly without altering any 'tweaks' - security should't be a tweak for nerds, it should be there for everyone - and we all agree in it. Not to mention that a lot so called tweaks are placebo. 
5. The section which mentioned Chrome vs. Firefox should be an own categorie because this project is about Mozilla Firefox and now about everythign else - keep the focus.
6. Since my time is very limited I might transfer the ownership to another person which is '_neutral_' like me.

Greetings,
CK

**Comment by CHEF-KOCH** [comment]
First discussion with Mozilla started, here is a recap of the webcam meeting I had today with one of the main developers (nope I not wanted to talk with someone from the marketing team - sorry!).

**The discussion ground was**:

1. How to handle the AMO Spam since the new addons not getting anymore manually reviewed?
2. The integration with user.js and the recent changes (58+ won't allow you to override it in the normal profile folder). Is there a feature to bring privacy between the community and Mozilla?!
3. What about the [pre-installed addons](https://chefkochblog.wordpress.com/2017/12/15/mozilla-firefox-installs-a-strange-looking-addon-without-asking-for-permission/)? 
4. We will talk about the install setup, I had some ideas which are related to Pocket and co, simply provide an 'advance' setup which offers 3 profiles like e.g. slim, normal and full .. based on that you get seperate profiles with addons enabled/disabled. Based on that it could solve point 2.
5. Integrated Mail support with [OpenPGP.js](https://github.com/openpgpjs/openpgpjs) encryption. LibreOffice recently added encryption to their own product, so why not Mozilla. OpenPGP.js is okay to use (well better than nothing!). However this requires a conversation between Mozilla, the community and (maybe as example [Mailvelope](https://github.com/mailvelope/mailvelope)).
6. Their roadmap (in detail) how to compete against other browsers and a statement about their Roadmap Page (which is a mess and confusing). I was thinking about a seperate page with details as per-year basis with the needed information, a seperate page for it's current implementation status. Not to mention that this should be maintained not only from the community.
7. Financial help for this project, to e.g. promote Firefox, give a advice for others to harden and setup Firfox and for research. These usually costs a lot of time and with this also money to get the needed information on a more serious way.
8. Firefox Quantum is doing great so far, [based on their blog post](https://blog.mozilla.org/press-de/2017/12/12/die-zeichen-stehen-auf-wachstum-erste-resonanz-zu-firefox-quantum/) - What does Mozilla do with the money to secure you? Why is it so difficult to find detailed information?


**Here ar the answers (in short)**:

1) There will be a advance scan in the store based on SHA checksums + the user can manually report addons. I can't give in public more information about their scanning method in detail.
2 + 4) This will be difficult to implement without breaking legit telemetry data, however it will be reviewed over the time. Since FF 58+ the focus is to harden your profiles, that's why the xxx.js loading thing got changed.
3) The addons are documented and it might get a change in the future to opt-in in every addon manually before it gets activated. There definitly trying to improve the current behavior.
5) There is no interest but it could be (again) internal picked up.
6) This is already planed for 2018.
7) This will be discussed with me internally not in public, however I will (as soon I get more support) make a paper about the current status & plans.
8) It was mentioned that there are already several pages but my counter argument that we only need one page and he gives it back to the marketing people to might improve it.

**Comment by CHEF-KOCH** [comment]
We already got money, I checked today my account and someone donated 800$ explicit for this little project here. I hope I can create an 'open' bank account next year. And I would like to use the money for:

1. Creating a professional logo 
2. A better gh page 
3. Opt-in into GitHub Pro to get our own 'domain' ^^ page
4. Buy some coffee for myself 
5. Research/meetings 
6. Use it to travel to events 
7. Whatever you guys tell me ....

**Comment by Atavic** [comment]
3. & 6. is the way. What kind of logo?

**Comment by CHEF-KOCH** [comment]
I have no idea which logo, that's something we need to check right now ... Should be a bit more serious and professional.

**Comment by Atavic** [comment]
Wow. Nice logo.
