### ISSUE TITLE
"Overview and goal" link loop

### ISSUE THREAD

**Issue by licaon-kter** [CHEF-KOCH/BetterFireFox#2]
Points back at the README.md

**Comment by CHEF-KOCH** [comment]
@licaon-kter You have access too, you can edit yourself, but if you wish, I can fix your mentioned things.

**Comment by licaon-kter** [comment]
I though you wanted to discuss issues first before submitting a PR/edit. :)

**Comment by CHEF-KOCH** [comment]
Yeah I not updated that, this is only for 'new' users, the ones which I have added from user.js are already trusted and have 'push' privileges. Feel free to edit what you want.  :+1:

**Comment by licaon-kter** [comment]
Fixed in https://github.com/CHEF-KOCH/BetterFireFox/commit/b95078a4fc62d26c958e807b285605bf5bde8e56
