### ISSUE TITLE
Copy of Chrome line

### ISSUE THREAD

**Issue by licaon-kter** [CHEF-KOCH/BetterFirefox#4]
This feels like a subtitle that has multiple bullet points underneath, that are missing now.

What was the thinking here, which issues from Chrome did creep up?

**Comment by CHEF-KOCH** [comment]
I think I will may change this soon with a reference link. It's unclear atm because it not mention the stuff which is copied (like safebrowsing integration). Maybe we general remove this and better list the stuff separately.
