### ISSUE TITLE
Give back control over the Browser line

### ISSUE THREAD

**Issue by licaon-kter** [CHEF-KOCH/BetterFirefox#7]
Feels like a repeat under the `opt-in` arguments above, maybe group them in: _things that need to be under user control_

**Comment by licaon-kter** [comment]
Fixed a bit in https://github.com/CHEF-KOCH/BetterFireFox/commit/b95078a4fc62d26c958e807b285605bf5bde8e56

Needs more work I guess.

**Comment by CHEF-KOCH** [comment]
If nothing more to say/add then i close this within the next 48 hours.
