### ISSUE TITLE
GH-Page added 

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/BetterFirefox#8]
Discussion ground
- I want to remove the 'CHEF-KOCH' tag and in url <code>https://chef-koch.github.io/BetterFirefox/</code> because it's community project (pending)
- Design and markdown to get a cleaner or better look?  (pending)
- Goal (I think) is to create this page to (one day or soon) hand it over to Mozilla so that they have an all-in-one page?
- _I currently experiment with the page so don't worry I will fix all the visible issue ...._
- Modded alpha-channel logo by W4RH4WK added. Original picture source: ??? 
- Organization created 12.12.2017 - https://github.com/BetterFirefox

Thread will be automatically cleaned to keep it on the topic, it's not against anyone. Everyone get mentioned here anyway which helped to improve stuff. Thanks guys.

**Comment by Gitoffthelawn** [comment]
Can you change the name from `BetterFireFox` to `BetterFirefox`?

**Comment by CHEF-KOCH** [comment]
Done.

**Comment by CHEF-KOCH** [comment]
Updated the page + theme. I hope it's okay :+1:

**Comment by W4RH4WK** [comment]
Does this work for you?

![ff](https://cloud.githubusercontent.com/assets/328798/16009425/f0fdb4c6-317c-11e6-9232-523dbf090f32.png)

**Comment by Atavic** [comment]
Mozilla Labs Test Pilot is the source of the logo. Project now gone.
Maybe you could create a new organization for this project?

**Comment by CHEF-KOCH** [comment]
Organization created and I invite known Firefox helpers, friends and supporters. 

What's important?
* The organization will be non-profitable, donations are welcome to improve Firefox and our team - I'll create a seperate pagefor this soon, the money goes on a bank account and every helper gets seperate access to it However this planed for 2018 and we need to discuss internal what we do with the money [if there is some money]).
* Everyone can join except; Mozilla or other 'profitable' organisations/employee because I not want to corupt the project, it should be open and transparent
* Maybe a kickstarter could help, I need several people with ideas and some know-how here to make a video, some whitepapers and maybe one for marketing

**Comment by W4RH4WK** [comment]
Using Google Image search, this might be the original source: https://blog.mozilla.org/addons/

**Comment by CHEF-KOCH** [comment]
@ W4RH4WK 

We will change the logo definitly but I'm bad at photoshop so I'm open if someone wants to do the dirty job, I'll also ask on other forums for help. I not want something which was original created under the mother brand 'Mozilla' - cause transparency.

**Comment by Atavic** [comment]
Just joined the [org](https://github.com/BetterFirefox), now this repo should be added to the org.

Moreover the org page should list more repositories: I told the same on [another](https://github.com/ghacksuserjs) org that has only one repo listed.

- Add the important repositories related to a better firefox browser: the repos to be added can be discussed or chosen from the most used ones (gorhill's ones come to mind).

- OSI Layers are ignored on most discussions about secure/private browsing, we should cite the OSI Layers to explain that an http:// URL on the Application Layer relates to a TCP request on the Transport Layer and relates to an IP address on the Internet Layer.

See: www.ggu.ac.in/download/Class-Note14/lesson13.02.14.pdf (Page 34)

- Other repo/orgs do not look at the broad spectrum: NSA lurks from the lowest OSI Layer upwards: the Network Interface. The attack surface is multilayered, first defense should be applied on the lowest layers available and not only to the browser.

**Comment by CHEF-KOCH** [comment]
We will not mention the ghacks-user.js or add it, _that's for sure_ - not only because my personal conflicts with some members there, moreover because the goal should be to reduce the effort and force Mozilla to provide a better method to solve this. It's still questionable if these tweaks help at all because most members using NoScript, uMatrix and co. and there is no point to block e.g. JavaScriptp when you anyway control it via uMatrix/Noscript. There is except more effort no security benefit and this project can't give any proof at all. There are more examples but I think everyone got the idea what I mean here, however if I'm the only one which thinks so, then I would not block anyone here to add it.... But again I see such tweaks not anymore as something which is mandatory to add to harden the browser, I think most issue are related to protocol/metadata because the Browser already get more features and fixes with each major version.

But I like the idea to add important projects into our organisation. Maybe someone can contact the owner of NoScript and uMatrix to allow us to add their repos here and add their names as supporter, I also would (of course) give them access to the organisation. 

The OSI layer idea is great, as said earlier in this post, I think most attacks are these days related to the protocols, and since there 30 years now I see them as weak, it's known and this can't be fixed except using newer and better protocols like Quic, HTTPS2 and others to secure the web on a modern standard. I will definitely mention this with the coming Readme update (end of this weekend).

The paper is interesting and easy to understand (more or less) I will integrate it into our repo I think we can write and work with it. However, keep in mind that networking is a huge project, and we can't cover every topic, I'm thankful if someone really wants to mention this but I'm a fan of solutions, which means pointing to known problems is fine but at least there should be some suggestions how to solve or workaround it. Saying HTTP is broken is not really helpful since you can't say stop using it, it would break too much right now, however what you then could say is to prefer HTTPS instead and guide people on which thinks they should look at.
